apps/twitter_server/web/router.ex
defmodule TwitterServer.Router do
  use TwitterServer.Web, :router
  import Plug.Conn

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TwitterServer.Auth, repo: TwitterServer.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  
  scope "/", TwitterServer do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index


    #custom
    get "/register", UserController, :register
    get "/signin", UserController, :new
    post "/signin", UserController, :signin
    get "/signout", UserController, :signout


    get "/users", UserController, :index
    get "/users/:id", UserController, :show
    post "/users", UserController, :create
    put "/users/:id", UserController, :update

    #timeline apis
    get "/timeline", TimelineController, :index



    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

  end
  

  # Other scopes may use custom stacks.
  # scope "/api", TwitterServer do
  #   pipe_through :api
  # end

  scope "/api", TwitterServer do
    pipe_through :api


    """
    get "/users", UserController, :index
    get "/users/:id", UserController, :show
    post "/users", UserController, :create
    put "/users/:id", UserController, :update
    """

    #login/logout

    #tweets api
    get "/tweets", TweetController, :index
    get "/tweets/:id", TweetController, :show
    post "/tweets/", TweetController, :create
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
       conn
    end
  end

end

apps/twitter_server/web/views/layout_view.ex
defmodule TwitterServer.LayoutView do
  use TwitterServer.Web, :view
end

apps/twitter_server/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TwitterServer!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <%= if logged_in?(@conn) do %>
        <li><%= current_user(@conn).email %></li>
        <li><%= link "Sign out", to: user_path(@conn, :signout) %></li>
      <% else %>
        <li><%= link "Sign In",    to: "/signin" %></li>
        <li><%= link "Register", to: user_path(@conn, :register) %></li>
      <% end %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>



      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
  
  
</html>